on:
  push:
    branches:
      - main
name: Deployment (paste)  
jobs:
  web-deploy:
    name: 🚀 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ${{ secrets.FTP_SERVER_PASTE }}
        ftp-username: ${{ secrets.FTP_USERNAME_PASTE }}
        ftp-password: ${{ secrets.FTP_PASSWORD_PASTE }}
